name: phone_blocker
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fluttertoast: ^7.1.4
  intl_phone_field: ^1.4.2
  google_sign_in: ^4.5.6
  http: ^0.12.0
  json_annotation: ^3.0.1
  intl_phone_number_input: ^0.5.2+2
  shared_preferences: ^0.5.12+4
  rate_my_app: ^0.7.1+1
  apple_sign_in: ^0.1.0
  flutter_secure_storage: ^3.3.5
  provider: ^4.0.1
  flutter_facebook_login: ^3.0.0


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^1.8.0
  json_serializable: ^3.3.0
  dalocale: ^2.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/login/
    - assets/intro/
    - assets/community/
    - assets/report/
    - assets/policy/
    - assets/flags/
    - assets/my_list/
    - assets/more/
    - assets/feedback/
    

